export interface WebSample {
  id: string;
  title: string;
  category: string;
  description: string;
  url: string;
  thumbnail: string;
  tags: string[];
  featured?: boolean;
}

export const WEB_SAMPLES: WebSample[] = [
  {
    id: "north-campers",
    title: "North Campers",
    category: "Resort & Hospitality",
    description: "Premium camping & outdoor adventure resort booking platform in northern mountain regions.",
    url: "https://north-campers.vercel.app/",
    thumbnail: "/assets/THUMBNAILS/NORTH CAMPERS.png",
    tags: ["Resort Booking", "Camping", "Outdoor Experience", "Next.js"],
    featured: true,
  },
  {
    id: "mugd",
    title: "MUGD Digital",
    category: "Digital Agency",
    description: "Modern web architecture and creative agency portfolio platform.",
    url: "https://mugd.vercel.app/",
    thumbnail: "/assets/THUMBNAILS/MUGD.png",
    tags: ["Agency", "Modern UI", "Interactive", "Portfolio"],
    featured: true,
  },
  {
    id: "pinecrest",
    title: "Pinecrest Resort",
    category: "Resort & Hospitality",
    description: "High-altitude mountain resort & eco-lodge stay reservation portal.",
    url: "https://pinecrest-sigma.vercel.app/",
    thumbnail: "/assets/THUMBNAILS/PINECREST.png",
    tags: ["Eco-Lodge", "Luxury Stay", "Reservation", "Mountain View"],
    featured: true,
  },
  {
    id: "travacations",
    title: "Travacations",
    category: "Travel & Vacations",
    description: "Curated vacation packages, tour itineraries, and travel booking engine.",
    url: "https://travacations.vercel.app/",
    thumbnail: "/assets/THUMBNAILS/TRAVACATIONS.png",
    tags: ["Travel Agency", "Tour Packages", "Booking Engine", "Destinations"],
    featured: true,
  },
  {
    id: "stoneyard",
    title: "The Stoneyard by Nomads",
    category: "Hospitality & Stays",
    description: "Boutique mountain retreat, luxury stay experience, and scenic dining.",
    url: "https://thestoneyardbynomads-livid.vercel.app/",
    thumbnail: "/assets/THUMBNAILS/STONEYARD.png",
    tags: ["Boutique Hotel", "Luxury Stays", "Nomads Experience", "Resort"],
    featured: true,
  },
  {
    id: "event-guardians",
    title: "Event Guardians",
    category: "Services & Security",
    description: "Professional event management, crowd safety, and security operations platform.",
    url: "https://event-guardians.vercel.app/",
    thumbnail: "/assets/THUMBNAILS/EVENT GUARDIANS.png",
    tags: ["Event Security", "Crowd Control", "Services", "Corporate"],
    featured: true,
  },
  {
    id: "autogarage",
    title: "Auto Garage Tag",
    category: "Automotive & Services",
    description: "Car care, repair tracking, garage appointment booking, and vehicle service hub.",
    url: "https://autogaragetag-seven.vercel.app/",
    thumbnail: "/assets/THUMBNAILS/AUTOGARAGE.png",
    tags: ["Automotive", "Garage Management", "Service Booking", "Car Care"],
  },
  {
    id: "secret-garden",
    title: "Secret Garden Kalam",
    category: "Resort & Hospitality",
    description: "Serene nature retreat and boutique garden lodge located in Kalam, Swat.",
    url: "https://secret-garden-kalam.vercel.app/",
    thumbnail: "/assets/THUMBNAILS/SECRET GARDEN.png",
    tags: ["Kalam Swat", "Garden Resort", "Hospitality", "Nature Stay"],
  },
  {
    id: "greystone-lodge",
    title: "Greystone Lodge Kalam",
    category: "Resort & Hospitality",
    description: "Luxury alpine lodge with panoramic valley view suites and dining in Kalam.",
    url: "https://greystone-lodge-kalam.vercel.app/",
    thumbnail: "/assets/THUMBNAILS/GREYSTONE LODGE.png",
    tags: ["Luxury Lodge", "Kalam Valley", "Alpine Resort", "Suites"],
  },
  {
    id: "adventurers",
    title: "Adventurers Delta",
    category: "Travel & Adventure",
    description: "Extreme sports, mountain trek expeditions, and group adventure tours platform.",
    url: "https://adventurers-delta.vercel.app/",
    thumbnail: "/assets/THUMBNAILS/ADVENTURERS.png",
    tags: ["Treks & Hikes", "Adventure Sports", "Expeditions", "Tours"],
  },
  {
    id: "shh",
    title: "SHH (Silent Haven Hostels)",
    category: "Hospitality & Stays",
    description: "Modern co-living accommodations and peaceful hostel reservation portal.",
    url: "https://shh-orpin.vercel.app/",
    thumbnail: "/assets/THUMBNAILS/SHH.png",
    tags: ["Co-Living", "Hostels", "Peaceful Stay", "Modern Accommodations"],
  },
  {
    id: "promptful",
    title: "Promptful Consulting",
    category: "Business & AI Consulting",
    description: "Strategic enterprise AI transformation, advisory, and corporate consulting web application.",
    url: "https://promptful-consulting.vercel.app/",
    thumbnail: "/assets/THUMBNAILS/PROMPTFUL.png",
    tags: ["AI Advisory", "Management Consulting", "Enterprise", "Corporate"],
  },
  {
    id: "khurasan-garden",
    title: "Khurasan Garden",
    category: "Dining & Events",
    description: "Scenic outdoor garden restaurant, family dining, and event venue showcase.",
    url: "https://khurasan-garden-xi.vercel.app/",
    thumbnail: "/assets/THUMBNAILS/KHURASAN GARDEN.png",
    tags: ["Garden Dining", "Event Venue", "Restaurant", "Family Stays"],
  },
  {
    id: "birmingham-ac",
    title: "Birmingham AC / AC Regas",
    category: "HVAC & Services",
    description: "Air conditioning repair, maintenance regas, and climate control booking portal.",
    url: "https://birmingham-ac.vercel.app/",
    thumbnail: "/assets/THUMBNAILS/AC REGAS.png",
    tags: ["HVAC Repair", "AC Regas", "Home Services", "Service Booking"],
  },
];
